# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    firewalls:
        #dev:
            #pattern: ^/(_(profiler|wdt)|css|images|js)/
            #security: false

        main:

            anonymous: ~
            # activate different ways to authenticate
            logout_on_user_change: true   
            